version: '3'

services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-iprody123}
      POSTGRES_DB: customer-service
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
        - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - backend

#  customer-service:
#    image: customer-service:latest
#    restart: always
#    ports:
#      - 8080:8080
#    networks:
#      - backend
#    depends_on:
#      - db
#      - pgAdmin

  pgAdmin:
    container_name: pg_admin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    volumes:
      - pgAdmin:/var/lib/pgadmin
    ports:
      - 8888:80
    depends_on:
      - db
    networks:
      - backend

volumes:
  database-data:
  pgAdmin:

networks:
  backend:
    driver: bridge
